
def dict_contains(data:dict, key,value) -> bool:
    return (key,value) in data.items()
        
def img_rec_json(json_input):
    """
    json_input can be a dict or string
    supposed to be generated by json.loads
    """
    if isinstance(json_input, dict):
        if dict_contains(json_input, 't', 'Image'):
            yield json_input
        else:
            for k, v in json_input.items(): 
                yield from img_rec_json(v)
    elif isinstance(json_input, list):
        for item in json_input:
            yield from img_rec_json(item)
            
def pandoc_img_name(pandoc_data:dict) -> str:
    """pandoc_data: a piece of pandoc data obtained by img_rec_json()
    """
    return pandoc_data['c'][-1][0]