backend:
  name: github

  # This line should *not* be indented
media_folder: "/markdown/assets" # Media files will be stored in the repo under images/uploads
public_folder: "/public/post/assets" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "blog"
    label: "Blog"
    folder: "/markdown"
    create: true # Allow users to create new documents in this collection
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}





